/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante.gui;

import restaurante.logica.Plato;
import restaurante.logica.acompañante.Acompañante;
import restaurante.logica.acompañante.Carbohidrato;

/**
 *
 * @author GOLDS
 */
public class JFrameMenuAcompañante2 extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMenuAcompañante2
     */
    
    private boolean pf;
    private boolean pl;
    private boolean yc;
    String c;
    Acompañante a;

    public String getC() {
        return c;
    }

    public void setC(String c) {
        this.c = c;
    }
    
    
    
    public JFrameMenuAcompañante2() {
        initComponents();
        pf=true;
        pl=true;
        yc=true;
        Plato p=new Plato();
        p.setA(a);
        a=new Carbohidrato();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPf = new javax.swing.JButton();
        jButtonYc = new javax.swing.JButton();
        jButtonPl = new javax.swing.JButton();
        jTextRes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonPf.setText("Papas Fritas");
        jButtonPf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPfActionPerformed(evt);
            }
        });

        jButtonYc.setText("Yuca");
        jButtonYc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonYcActionPerformed(evt);
            }
        });

        jButtonPl.setText("Platano");
        jButtonPl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonYc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65)
                .addComponent(jTextRes, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextRes)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonYc)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPl)))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPfActionPerformed
        pf=false;
        pl=true;
        yc=true;
        this.c=a.getPapasFritas();
        jTextRes.setText(a.getPapasFritas());
    }//GEN-LAST:event_jButtonPfActionPerformed

    private void jButtonYcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYcActionPerformed
        pf=true;
        pl=false;
        yc=true;
        this.c=a.getPlatano();
        jTextRes.setText(a.getPlatano());
    }//GEN-LAST:event_jButtonYcActionPerformed

    private void jButtonPlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlActionPerformed
        pf=true;
        pl=true;
        yc=false;
        this.c=a.getYuca();
        jTextRes.setText(a.getYuca());
    }//GEN-LAST:event_jButtonPlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuAcompañante2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuAcompañante2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuAcompañante2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuAcompañante2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMenuAcompañante2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButtonPf;
    javax.swing.JButton jButtonPl;
    javax.swing.JButton jButtonYc;
    javax.swing.JTextField jTextRes;
    // End of variables declaration//GEN-END:variables
}
