/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante.gui;

import restaurante.logica.Plato;
import restaurante.logica.acompañante.Acompañante;
import restaurante.logica.acompañante.Carbohidrato;
import restaurante.logica.acompañante.Ensalada;
import restaurante.logica.base.Arroz;
import restaurante.logica.base.Base;
import restaurante.logica.base.Proteina;
import restaurante.logica.bebida.Bebida;
import restaurante.logica.bebida.Gaseosa;
import restaurante.logica.bebida.Jugo;

/**
 *
 * @author GOLDS
 */
public class JFrameMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu2
     */
    
    public String rs1;
    private boolean ar;
    private boolean car;
    private boolean ens;
    private boolean otro;
    private boolean jg;
    private boolean gs;
    Bebida bb;
    Acompañante a;
    Base b;
    JFrameMenuBase2 carne= new JFrameMenuBase2();
    JFrameMenuBase arroz= new JFrameMenuBase();
    JFrameMenuAcompañante ensalada= new JFrameMenuAcompañante();
    JFrameMenuAcompañante2 carbohidrato= new JFrameMenuAcompañante2();
    JFrameMenuBebida jugo= new JFrameMenuBebida();
    JFrameMenuBebida2 gaseosa= new JFrameMenuBebida2();
   
    
    public JFrameMenu() {
        initComponents();
        ar=true;
        car=true;
        ens=true;
        otro=true;
        jg=true;
        gs=true;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonBA = new javax.swing.JButton();
        jButtonBC = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextPane10 = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jButtonAE = new javax.swing.JButton();
        jButtonAO = new javax.swing.JButton();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextPane11 = new javax.swing.JTextPane();
        jPanel4 = new javax.swing.JPanel();
        jButtonBJ = new javax.swing.JButton();
        jButtonBG = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextPane12 = new javax.swing.JTextPane();
        jButtonGenerar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPlato = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonBA.setText("Arroces");
        jButtonBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBAActionPerformed(evt);
            }
        });

        jButtonBC.setText("Carnes");
        jButtonBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBCActionPerformed(evt);
            }
        });

        jTextPane10.setText("Bases");
        jScrollPane11.setViewportView(jTextPane10);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane11)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonBA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(jButtonBC, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(109, 109, 109))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBA)
                    .addComponent(jButtonBC))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonAE.setText("Ensaldas");
        jButtonAE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAEActionPerformed(evt);
            }
        });

        jButtonAO.setText("Otros");
        jButtonAO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAOActionPerformed(evt);
            }
        });

        jTextPane11.setText("Acompañantes");
        jScrollPane12.setViewportView(jTextPane11);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonAE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAO, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAE)
                    .addComponent(jButtonAO))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonBJ.setText("Jugos");
        jButtonBJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBJActionPerformed(evt);
            }
        });

        jButtonBG.setText("Gaseosas");
        jButtonBG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBGActionPerformed(evt);
            }
        });

        jTextPane12.setText("Bebidas");
        jScrollPane13.setViewportView(jTextPane12);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButtonBJ, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBG))
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBG)
                    .addComponent(jButtonBJ))
                .addContainerGap())
        );

        jButtonGenerar.setText("GENERAR");
        jButtonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarActionPerformed(evt);
            }
        });

        jTextField1.setText("RESTAURANTE LA 40");

        jTextField2.setText("MENU");

        jTextPlato.setColumns(20);
        jTextPlato.setRows(5);
        jScrollPane7.setViewportView(jTextPlato);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jButtonGenerar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGenerar))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane7))
                .addGap(0, 45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBAActionPerformed

      ar=false;
      car=true;
      Plato p=new Plato();
      p.setB(b);
      b=new Arroz();
      carne.setVisible(false);
      arroz.setVisible(true);
      ensalada.setVisible(false);
      carbohidrato.setVisible(false);
      jugo.setVisible(false);
      gaseosa.setVisible(false);
     
    }//GEN-LAST:event_jButtonBAActionPerformed

    private void jButtonBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBCActionPerformed
      arroz.setVisible(false);
      carne.setVisible(true);
      ensalada.setVisible(false);
      carbohidrato.setVisible(false);
      jugo.setVisible(false);
      gaseosa.setVisible(false);
      car = false;
      ar=true;
      Plato p=new Plato();
      p.setB(b);
      b=new Proteina();
      
    }//GEN-LAST:event_jButtonBCActionPerformed

    private void jButtonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarActionPerformed
    
     jTextPlato.setText("TU PLATO ES : \n");
        
    if (ar==false && car==true){
        jTextPlato.setText(jTextPlato.getText()+"Arroz  "+arroz.getA()+"\n");
    }else{
        jTextPlato.setText(jTextPlato.getText()+carne.getG()+"\n");
    }
    if (ens==false && otro==true){
        jTextPlato.setText(jTextPlato.getText()+ensalada.getE()+"\n");   
    }else{
        jTextPlato.setText(jTextPlato.getText()+carbohidrato.getC()+"\n");
    }
    if (jg==false && gs==true){
        jTextPlato.setText(jTextPlato.getText()+"Jugo "+jugo.getJ()+"\n");
    }else{
        jTextPlato.setText(jTextPlato.getText()+"Gaseosa "+gaseosa.getGg()+"\n");
    }
    
    
    
    }//GEN-LAST:event_jButtonGenerarActionPerformed

    private void jButtonAEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAEActionPerformed
       
      arroz.setVisible(false);
      carne.setVisible(false);
      ensalada.setVisible(true);
      carbohidrato.setVisible(false);
      jugo.setVisible(false);
      gaseosa.setVisible(false);
       ens=false;
       otro=true;
       Plato p=new Plato();
       p.setA(a);
       a=new Ensalada();
       
       
    }//GEN-LAST:event_jButtonAEActionPerformed

    private void jButtonAOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAOActionPerformed
       
       ensalada.setVisible(false);
       carbohidrato.setVisible(true);
       jugo.setVisible(false);
       gaseosa.setVisible(false);
       ens=true;
       otro=false;
       Plato p=new Plato();
       p.setA(a);
       a=new Carbohidrato();
    }//GEN-LAST:event_jButtonAOActionPerformed

    private void jButtonBJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBJActionPerformed
       
       arroz.setVisible(false);
      carne.setVisible(true);
      ensalada.setVisible(false);
      carbohidrato.setVisible(false);
      jugo.setVisible(true);
      gaseosa.setVisible(false);
       jg=false;
       gs=true;
       Plato p=new Plato();
       p.setBb(bb);
       bb=new Jugo();
    }//GEN-LAST:event_jButtonBJActionPerformed

    private void jButtonBGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBGActionPerformed
       arroz.setVisible(false);
      carne.setVisible(true);
      ensalada.setVisible(false);
      carbohidrato.setVisible(false);
      jugo.setVisible(false);
      gaseosa.setVisible(true);
       jg=true;
       gs=false;
       Plato p=new Plato();
       p.setBb(bb);
       bb=new Gaseosa();
    }//GEN-LAST:event_jButtonBGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButtonAE;
    javax.swing.JButton jButtonAO;
    javax.swing.JButton jButtonBA;
    javax.swing.JButton jButtonBC;
    javax.swing.JButton jButtonBG;
    javax.swing.JButton jButtonBJ;
    javax.swing.JButton jButtonGenerar;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel3;
    javax.swing.JPanel jPanel4;
    javax.swing.JScrollPane jScrollPane11;
    javax.swing.JScrollPane jScrollPane12;
    javax.swing.JScrollPane jScrollPane13;
    javax.swing.JScrollPane jScrollPane7;
    javax.swing.JTextField jTextField1;
    javax.swing.JTextField jTextField2;
    javax.swing.JTextPane jTextPane10;
    javax.swing.JTextPane jTextPane11;
    javax.swing.JTextPane jTextPane12;
    javax.swing.JTextArea jTextPlato;
    // End of variables declaration//GEN-END:variables
}
