/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante.gui;

import restaurante.logica.Plato;
import restaurante.logica.acompañante.Acompañante;
import restaurante.logica.acompañante.Carbohidrato;
import restaurante.logica.acompañante.Ensalada;
import restaurante.logica.base.Arroz;
import restaurante.logica.base.Base;
import restaurante.logica.base.Proteina;
import restaurante.logica.bebida.Bebida;
import restaurante.logica.bebida.Gaseosa;
import restaurante.logica.bebida.Jugo;


/**
 *
 * @author GOLDS
 */
public class JFrameMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu2
     */
    
    public String rs1;
    private boolean ar;
    private boolean car;
    private boolean ens;
    private boolean otro;
    private boolean jg;
    private boolean gs;
    Bebida bb;
    Acompañante a;
    Base b;
    JFrameMenuBase2 carne= new JFrameMenuBase2();
    JFrameMenuBase arroz= new JFrameMenuBase();
    JFrameMenuAcompañante ensalada= new JFrameMenuAcompañante();
    JFrameMenuAcompañante2 carbohidrato= new JFrameMenuAcompañante2();
    JFrameMenuBebida jugo= new JFrameMenuBebida();
    JFrameMenuBebida2 gaseosa= new JFrameMenuBebida2();
   
    
    public JFrameMenu() {
        initComponents();
        ar=true;
        car=true;
        ens=true;
        otro=true;
        jg=true;
        gs=true;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonBA = new javax.swing.JButton();
        jButtonBC = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextPane10 = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jButtonAE = new javax.swing.JButton();
        jButtonAO = new javax.swing.JButton();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextPane11 = new javax.swing.JTextPane();
        jPanel4 = new javax.swing.JPanel();
        jButtonBJ = new javax.swing.JButton();
        jButtonBG = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextPane12 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPl = new javax.swing.JTextArea();
        jButtonGenerar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPl2 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPl3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPl4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPl5 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPl6 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonBA.setText("Arroces");
        jButtonBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBAActionPerformed(evt);
            }
        });

        jButtonBC.setText("Carnes");
        jButtonBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBCActionPerformed(evt);
            }
        });

        jTextPane10.setText("Bases");
        jScrollPane11.setViewportView(jTextPane10);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane11)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonBA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(jButtonBC, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(109, 109, 109))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBA)
                    .addComponent(jButtonBC))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 440, 80));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonAE.setText("Ensaldas");
        jButtonAE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAEActionPerformed(evt);
            }
        });

        jButtonAO.setText("Otros");
        jButtonAO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAOActionPerformed(evt);
            }
        });

        jTextPane11.setText("Acompañantes");
        jScrollPane12.setViewportView(jTextPane11);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonAE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAO, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAE)
                    .addComponent(jButtonAO))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 440, 60));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonBJ.setText("Jugos");
        jButtonBJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBJActionPerformed(evt);
            }
        });

        jButtonBG.setText("Gaseosas");
        jButtonBG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBGActionPerformed(evt);
            }
        });

        jTextPane12.setText("Bebidas");
        jScrollPane13.setViewportView(jTextPane12);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButtonBJ, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBG))
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBG)
                    .addComponent(jButtonBJ))
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 440, 70));

        jTextPl.setColumns(20);
        jTextPl.setRows(5);
        jScrollPane3.setViewportView(jTextPl);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 80, 70));

        jButtonGenerar.setText("GENERAR");
        jButtonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));

        jTextField1.setText("RESTAURANTE LA 40");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 620, 40));

        jTextField2.setText("MENU");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 440, -1));

        jTextPl2.setColumns(20);
        jTextPl2.setRows(5);
        jScrollPane1.setViewportView(jTextPl2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 80, 60));

        jTextPl3.setColumns(20);
        jTextPl3.setRows(5);
        jScrollPane2.setViewportView(jTextPl3);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 80, 70));

        jTextPl4.setColumns(20);
        jTextPl4.setRows(5);
        jScrollPane4.setViewportView(jTextPl4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 80, 70));

        jTextPl5.setColumns(20);
        jTextPl5.setRows(5);
        jScrollPane5.setViewportView(jTextPl5);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 80, 60));

        jTextPl6.setColumns(20);
        jTextPl6.setRows(5);
        jScrollPane6.setViewportView(jTextPl6);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 80, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBAActionPerformed

      ar=false;
      car=true;
      Plato p=new Plato();
      p.setB(b);
      b=new Arroz();
      carne.setVisible(false);
      arroz.setVisible(true);
     
    }//GEN-LAST:event_jButtonBAActionPerformed

    private void jButtonBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBCActionPerformed
      arroz.setVisible(false);
      carne.setVisible(true);
      car = false;
      ar=true;
      Plato p=new Plato();
      p.setB(b);
      b=new Proteina();
      
    }//GEN-LAST:event_jButtonBCActionPerformed

    private void jButtonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarActionPerformed
    
    
    jTextPl.setText(carne.getG());
    jTextPl4.setText(arroz.getA());
    jTextPl2.setText(ensalada.getE());
    jTextPl5.setText(carbohidrato.getC());
    jTextPl3.setText(gaseosa.getGg());
    jTextPl6.setText(jugo.getJ());
    
    }//GEN-LAST:event_jButtonGenerarActionPerformed

    private void jButtonAEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAEActionPerformed
       
       ensalada.setVisible(true);
       carbohidrato.setVisible(false);
       ens=false;
       otro=true;
       Plato p=new Plato();
       p.setA(a);
       a=new Ensalada();
       
       
    }//GEN-LAST:event_jButtonAEActionPerformed

    private void jButtonAOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAOActionPerformed
       
       ensalada.setVisible(false);
       carbohidrato.setVisible(true);
       ens=true;
       otro=false;
       Plato p=new Plato();
       p.setA(a);
       a=new Carbohidrato();
    }//GEN-LAST:event_jButtonAOActionPerformed

    private void jButtonBJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBJActionPerformed
       
       jugo.setVisible(true);
       gaseosa.setVisible(false);
       jg=false;
       gs=true;
       Plato p=new Plato();
       p.setBb(bb);
       bb=new Jugo();
    }//GEN-LAST:event_jButtonBJActionPerformed

    private void jButtonBGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBGActionPerformed
       jugo.setVisible(false);
       gaseosa.setVisible(true);
       jg=true;
       gs=false;
       Plato p=new Plato();
       p.setBb(bb);
       bb=new Gaseosa();
    }//GEN-LAST:event_jButtonBGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButtonAE;
    javax.swing.JButton jButtonAO;
    javax.swing.JButton jButtonBA;
    javax.swing.JButton jButtonBC;
    javax.swing.JButton jButtonBG;
    javax.swing.JButton jButtonBJ;
    javax.swing.JButton jButtonGenerar;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel3;
    javax.swing.JPanel jPanel4;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JScrollPane jScrollPane11;
    javax.swing.JScrollPane jScrollPane12;
    javax.swing.JScrollPane jScrollPane13;
    javax.swing.JScrollPane jScrollPane2;
    javax.swing.JScrollPane jScrollPane3;
    javax.swing.JScrollPane jScrollPane4;
    javax.swing.JScrollPane jScrollPane5;
    javax.swing.JScrollPane jScrollPane6;
    javax.swing.JTextField jTextField1;
    javax.swing.JTextField jTextField2;
    javax.swing.JTextPane jTextPane10;
    javax.swing.JTextPane jTextPane11;
    javax.swing.JTextPane jTextPane12;
    javax.swing.JTextArea jTextPl;
    javax.swing.JTextArea jTextPl2;
    javax.swing.JTextArea jTextPl3;
    javax.swing.JTextArea jTextPl4;
    javax.swing.JTextArea jTextPl5;
    javax.swing.JTextArea jTextPl6;
    // End of variables declaration//GEN-END:variables
}
