/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante.gui;

import restaurante.logica.Plato;
import restaurante.logica.bebida.Bebida;
import restaurante.logica.bebida.Jugo;

/**
 *
 * @author GOLDS
 */
public class JFrameMenuBebida extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMenuBebida
     */
    private boolean mor;
    private boolean man;
    private boolean ll;
    String j;
    Bebida bb;

    public String getJ() {
        return j;
    }

    public void setJ(String j) {
        this.j = j;
    }
    
    
    public JFrameMenuBebida() {
        initComponents();
        mor=true;
        man=true;
        ll=true;
        Plato p= new Plato();
        p.setBb(bb);
        bb=new Jugo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonMr = new javax.swing.JButton();
        jButtonMn = new javax.swing.JButton();
        jButtonLl = new javax.swing.JButton();
        jTextRes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonMr.setText("Mora");
        jButtonMr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMrActionPerformed(evt);
            }
        });

        jButtonMn.setText("Mango");
        jButtonMn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMnActionPerformed(evt);
            }
        });

        jButtonLl.setText("Lulo");
        jButtonLl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonMn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(61, 61, 61)
                .addComponent(jTextRes, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonMr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonMn)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLl))
                    .addComponent(jTextRes))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMrActionPerformed
        mor=false;
        man=true;
        ll=true;
        this.j=bb.getMora();
        jTextRes.setText(bb.getMora());
    }//GEN-LAST:event_jButtonMrActionPerformed

    private void jButtonMnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMnActionPerformed
        mor=true;
        man=false;
        ll=true;
        this.j=bb.getMango();
        jTextRes.setText(bb.getMango());
    }//GEN-LAST:event_jButtonMnActionPerformed

    private void jButtonLlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLlActionPerformed
        mor=true;
        man=true;
        ll=false;
        this.j=bb.getLulo();
        jTextRes.setText(bb.getLulo());
    }//GEN-LAST:event_jButtonLlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMenuBebida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButtonLl;
    javax.swing.JButton jButtonMn;
    javax.swing.JButton jButtonMr;
    javax.swing.JTextField jTextRes;
    // End of variables declaration//GEN-END:variables
}
